// data/programData.js

export const programCards = [
  {
    id: 1,
    title: "Data Science and GenAI Master Certification Program",
    description:
      "Master GenAI Expertise and Build Industry-Ready Projects fusing LangChain and AgenticAI.",
    why: [
      "Build AI-powered applications",
      "Master prompt engineering techniques",
    ],
    keySkills: ["ChatGPT", "Claude", "Prompt Engineering"],
    duration: " 13 Months",
    level: "18+ Skill Based",
    eligibilitytitle: "Program Eligibility :",
    eligibility: "From Learnbay and partnered companies",
    readyfor: "Industry-Ready Certification",
    brochureUrl: "#",
    projects: "Projects:",
    theme: "chocolateOrange",
    logo: "https://d32and0ii3b8oy.cloudfront.net/web/s3_main/new-UI/ibm-microsoft+(1).webp",
    icon: "https://d32and0ii3b8oy.cloudfront.net/web/s3_main/Group+2408.webp",
  },

  {
    id: 2,
    title: "Full Stack Software Development Master Certification",
    description:
      "Enhance your career with Front-end, Back-end development skills and GenAI integration",
    why: ["Learn how to build Web Applications and Full-Stack Systems"],
    keySkills: ["ChatGPT", "MERN", "API’s & Web Services"],
    duration: " 12 Months",
    level: "Unlimited Interview Calls",
    eligibility: "Interactive Problem Solving &",
    secondeligibilitytitle: " Interview Preparation",
    readyfor: "Get Job Ready For",
    brochureUrl: "#",
    theme: "purple",
    logo: "https://d32and0ii3b8oy.cloudfront.net/web/s3_main/Group+2673.webp",
    icon: "https://d32and0ii3b8oy.cloudfront.net/web/s3_main/Group+2369.webp",
  },
  {
    id: 3,
    title: "Cloud and DevOps Engineering Master Certification Program",
    description:
      "Learn how to streamline deployments & scale cloud infrastructure with automation using GenAI",
    why: ["Master containerization", "Implement CI/CD Pipelines"],
    keySkills: ["ChatGPT", "GitOps", "Jenkins", "DevSecOps"],
    duration: " 10 Months",
    level: "12+ Skill Based",
    eligibility: "Unlimited mock interviews and ",
    secondeligibilitytitle: "personalized job calls",
    readyfor: "Be an Expert Using",
    brochureUrl: "#",
    projects: "Projects:",
    theme: "green",
    logo: "https://d32and0ii3b8oy.cloudfront.net/web/s3_main/Group+2682+(1).webp",
    icon: "https://d32and0ii3b8oy.cloudfront.net/web/learnbay_v4/Homepage/course_section/devops_icon.png",
  },
  {
    id: 4,
    title: "Cybersecurity & Digital Defense Master",
    description:
      "Safeguard digital assets & design robust, secure systems from the ground up using GenAI",
    why: ["Master ethical hacking techniques", "Design secure systems"],
    keySkills: ["Kali Linux", "Burp Suite", "Prompt Engineering"],
    duration: " 11 Months",
    level: "18+ Real-Time",
    eligibility: "Job placement opportunities in top cybersecurity firms",
    brochureUrl: "#",
    projects: "Projects:",
    readyfor: "Certification from Industry Leader",
    theme: "violet",
    logo: "https://d32and0ii3b8oy.cloudfront.net/web/s3_main/Group+2675.webp",
    icon: "https://d32and0ii3b8oy.cloudfront.net/web/learnbay_v4/Homepage/course_section/cyber_security_cion.png",
  },
];
